// script.js
let cart = [];

function addToCart(productName, price) {
  cart.push({ productName, price });
  alert(`${productName} wurde zum Warenkorb hinzugefügt.`);
}

function viewCart() {
  let cartItems = "Warenkorb:\n";
  let totalPrice = 0;

  for (let item of cart) {
    cartItems += `${item.productName} - $${item.price}\n`;
    totalPrice += item.price;
  }

  cartItems += `\nGesamt: $${totalPrice}`;
  alert(cartItems);
}
